#!/usr/bin/env bash
#MISE description="基本パッケージのインストール"

set -e

if command -v gcc &> /dev/null; then
  echo "build-essential already installed"
  exit 0
fi

if command -v apt &> /dev/null; then
  echo "Installing build-essential..."
  sudo apt update && sudo apt install -y build-essential curl git zsh
elif command -v dnf &> /dev/null; then
  sudo dnf groupinstall -y "Development Tools"
  sudo dnf install -y curl git zsh
fi
